networks:
  cloudflared-net:
    name: cloudflared-net
  backup-scheduler-net:
    name: backup-scheduler-net

services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared
    restart: always
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    networks:
      - cloudflared-net
    command: tunnel --no-autoupdate run
  backup-scheduler:
    container_name: backup-scheduler
    build: .
    restart: always
    environment:
      BACKUP_SCHEDULER_CRON_PATTERN: ${BACKUP_SCHEDULER_CRON_PATTERN}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_ENDPOINT: ${S3_ENDPOINT}
    volumes:
      - ${BACKUP_SCHEDULER_CONFIG_FILE}:/app/backup-scheduler.json
    networks:
      - backup-scheduler-net
