name: core-infra-devcontainer

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}-net

services:
  backup-scheduler-db:
    container_name: ${COMPOSE_PROJECT_NAME}-backup-scheduler-db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: backup-scheduler
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  workspace:
    container_name: ${COMPOSE_PROJECT_NAME}-workspace
    image: oven/bun:1.2-alpine
    command: sleep infinity
    depends_on:
      - backup-scheduler-db
    volumes:
      - ../.:/workspace:cached
