name: deployment-platform

volumes:
  backups-database-data:
  backups-storage-data:

services:
  backups-database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - backups-database-data:/var/lib/postgresql/data
  backups-storage:
    image: localstack/localstack
    environment:
      SERVICES: s3
      PERSISTENCE: 1
    volumes:
      - backups-storage-data:/var/lib/localstack
  backups:
    image: oven/bun:1.2-alpine
    command: sleep infinity
    depends_on:
      - backups-database
      - backups-storage
    volumes:
      - ../.:/workspace:cached
