name: core-infra-devcontainer

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}-net

services:
  backup-scheduler-database:
    container_name: ${COMPOSE_PROJECT_NAME}-backup-scheduler-database
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  workspace:
    container_name: ${COMPOSE_PROJECT_NAME}-workspace
    image: oven/bun:1.2-alpine
    command: sleep infinity
    depends_on:
      - backup-scheduler-database
    volumes:
      - ../.:/workspace:cached
